### PR TITLE
Block user

### PR DESCRIPTION
**Pull request by steventt07**

### CODE REVIEW

**Comment by steventt07** [comment]
Can you add alerts associated with the block user action?

**Comment by npasricha-cs** [comment]
Is this functionality working in the front end or is it only in the back end?

**Comment by npasricha-cs** [comment]
I can create the alert for this

**Comment by npasricha-cs** [comment]
There are bugs. When reporting a post it says you cannot block yourself, when reporting a comment it takes you to report page then throws alert for blocking someone while there lol 

Looking into it

**Pull request merged**
