### PR TITLE
Holy fuck I did it

### PR DESCRIPTION
**Pull request by npasricha-cs**

### CODE REVIEW

**Comment by steventt07** [comment]
Two small changes. Nav arrow shows in FeedView and LikedListView. Also coloring is not consistent with LikeListView.
Screen Shot 2021-05-10 at 6 25 17 PM
Screen Shot 2021-05-10 at 6 25 05 PM

**Comment by npasricha-cs** [comment]
Liked hasn't been updated in a while that's unrelated. Also removing the arrow is going to be another fix since we removed it the first time by multiplying over it. Will have to do those in separate branches

**Comment by npasricha-cs** [comment]
I can update likedlistview but the navigation arrow is a weird thing

**Comment by npasricha-cs** [comment]
No idea how the fuck to fix the arrow from nav link lmao I tried

Fixed the UserLikedList though

**Pull request merged**
