### PR TITLE
finish password recovery and registartion pages rework

### PR DESCRIPTION
**Pull request by steventt07**

### CODE REVIEW

**Comment by bubble-software** [comment]
My date for testing is Monday the 31

**Comment by npasricha-cs** [comment]
This part about "choose a name will keep you hidden" seems overly aggressive and doesn't make much sense

Everyone chooses a name on every platform in existence except a handful these days, we don't need to say anything more than "Bubble is an anonymous platform. Choose the username to associate with your profile".

**Comment by npasricha-cs** [comment]
Also there is no submit button for entering the username, need to have that.

**Comment by npasricha-cs** [comment]
Or submit button for entering the email

**Comment by npasricha-cs** [comment]
Need to have back buttons as well in case they typed something wrong. For the password input they should enter it twice/we need to validate it has all the characters properly.

**Comment by npasricha-cs** [comment]
Should also only validate on one email/account

**Comment by npasricha-cs** [comment]
Did not get an email code to my account

**Comment by npasricha-cs** [comment]
approved

**Pull request merged**
